---

- hosts: all 
  become: true
  tasks:

  - name: update repository index
    package:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd for CentOS
    package:
      name: httpd
    when: ansible_distribution == "CentOS"
